version: '3'
#networks:
#  fastdfs-net:
#    external: true
networks:
  fastdfs-net:
    driver: bridge
services:
  tracker:
    container_name: tracker
    image: ygqygq2/fastdfs-nginx:latest
    command: tracker
    #network_mode: host
    networks:
      - fastdfs-net
    volumes:   
      - /var/fdfs/tracker:/var/fdfs    
    ports:
      - 22122:22122
  storage0:
    container_name: storage0
    image: ygqygq2/fastdfs-nginx:latest
    command: storage
    #network_mode: host  
    networks:
      - fastdfs-net
    environment:
      - TRACKER_SERVER=tracker:22122
    volumes: 
      - /var/fdfs/storage0:/var/fdfs
    ports:
      - 28080:8080
  storage1:
    container_name: storage1
    image: ygqygq2/fastdfs-nginx:latest
    command: storage
    #network_mode: host  
    networks:
      - fastdfs-net
    environment:
      - TRACKER_SERVER=tracker:22122
    volumes: 
      - /var/fdfs/storage1:/var/fdfs
    ports:
      - 28081:8080
